### ISSUE TITLE
UWP sample cannot work properly

### ISSUE THREAD

**Issue by shugaoye** [messier16/MarkdownView2#1]
I tested the sample. Both Android and iOS look good. However, UWP just display an empty screen. Do you know why ? 

Is this the right path to find resources ?
"ms-appx-web:///Assets/"

**Comment by fferegrino** [comment]
I'm running it perfectly fine, would you mind sharing your development setup?

![capture](https://user-images.githubusercontent.com/1820946/43164747-e8b76970-8f89-11e8-8441-f3a6cdff20a7.PNG)

**Comment by shugaoye** [comment]
Thanks! I have fixed the issue. It works fine now.
